### ISSUE TITLE
'float DHT::readHumidity()' is private

### ISSUE THREAD

**Issue by jrubinstein** [russgrue/Adafruit_DHT_Library#1]
Veryfing code using this library in Particle Build fails with this error:
```
Adafruit_DHT/Adafruit_DHT.h:34:9: error: 'float DHT::readHumidity()' is private
   float readHumidity(void)

**Comment by russgrue** [comment]
That doesn't appear to be the case with the actual code.  It may be a peculiarity in the new Particle system.  I'll have a look at it later today.

**Comment by jrubinstein** [comment]
Thanks @russgrue!  This is just the error message I received when trying to use the DHT library. I am using the web IDE.

**Comment by russgrue** [comment]
Just recompiled a fresh pull of the library in the Particle IDE using the DHT_TEST.ino and it worked fine.

Try removing and re-inserting the library and recompiling.  If that doesn't work include your firmware code here and I'll see if I can spot anything wrong in your code.

**Comment by jrubinstein** [comment]
Still having problems (albeit different ones) 
Went to libraries Adafruit_DHT
"use example", then "verify"
This is the error I get:
![screen shot 2015-07-01 at 6 58 02 pm](https://cloud.githubusercontent.com/assets/2230712/8468633/94b08f06-2023-11e5-9d7d-e792118b59e5.png)

**Comment by russgrue** [comment]
You've got the path wrong in the include, when you copy the code out of the library and into the firmware you need to include the path of the library itself.

**Comment by jrubinstein** [comment]
Can you provide an example? I'm just telling build.particle to include the
library.

**Comment by jrubinstein** [comment]
Okay, I figured it out :) 
it's #include "Adafruit_DHT/Adafruit_DHT.h" 
It's now working!! Thanks for your help, @russgrue !
